# frozen_string_literal: true

require 'fileutils'

module CV
  # Renders the LaTeX CV from data/*.yml + personal.bib using
  # templates/latex/cv.tex.erb. This is the source of the published PDFs.
  #
  # `build` writes the document body (build/cv.tex) plus three thin wrappers
  # that select a variant before \input-ing it — the same pattern the old
  # handcrafted latex/{public,unredacted}.tex used:
  #
  #   cv-full.tex        full CV; referee phone numbers suppressed (\refphone)
  #   cv-public.tex      \publicversion — references replaced with "available
  #                      upon request"; this is the PDF served at the site root
  #   cv-unredacted.tex  \unredacted — includes referee phone numbers. Private:
  #                      gitignored, never built or deployed by CI.
  #
  # Compile with `latexmk -lualatex` from inside build/ so \input{cv} resolves
  # (the moderncv setup needs lualatex because of fontspec).
  module Latex
    DEFAULT_OUTPUT = CV::BUILD_DIR.join('cv.tex')

    # wrapper basename => the macro it defines before \input{cv} ('' = none)
    VARIANTS = {
      'cv-full'       => nil,
      'cv-public'     => 'publicversion',
      'cv-unredacted' => 'unredacted'
    }.freeze

    module_function

    def build(output: DEFAULT_OUTPUT, data: nil, bib: nil)
      data ||= CV::Data.load
      bib  ||= CV::Bib.load
      tex = CV::Renderer.new(format: :latex)
                        .render('cv.tex', data: data, bib: bib)
      FileUtils.mkdir_p(File.dirname(output))
      File.write(output, tex)
      write_variants(File.dirname(output), File.basename(output, '.tex'))
      output
    end

    # Emit the wrapper documents next to the body. Regenerated on every build
    # so they can never drift from VARIANTS.
    def write_variants(dir, body_basename)
      VARIANTS.map do |name, macro|
        path = File.join(dir, "#{name}.tex")
        File.write(path, <<~TEX)
          % Generated by bin/cv tex — do not edit. Wraps #{body_basename}.tex.
          #{macro ? "\\def\\#{macro}{1}\n" : ''}\\input{#{body_basename}}
        TEX
        path
      end
    end
  end
end
